services:
  pipeline-db:
    image: mysql:8.0
    container_name: pipeline-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: libros_db
    networks:
      - pipeline-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  pipeline-web:
    image: urva123ishfaq/libros-app:latest
    container_name: pipeline-web
    restart: unless-stopped
    depends_on:
      pipeline-db:
        condition: service_healthy
    environment:
      DB_HOST: pipeline-db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: libros_db
      SECRET_KEY: superSecretKey456
    ports:
      - "5001:5000"
    networks:
      - pipeline-net

networks:
  pipeline-net:
    driver: bridge
